### ISSUE TITLE
Do I need to change the label of the sim10k?

### ISSUE THREAD

**Issue by VincentZFY** [ChrisAllenMing/GPA-detection#19]
Hi! I really appreciate your work and I want to run your code to learn from it . But I met with the following error ,is there a mistake when I deal with the sim10k dataset,I just simply download the dataset and put the anno,images like cityscapes:
```
Traceback (most recent call last):
  File "train_GPA.py", line 304, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "./lib/roi_data_layer/roidb.py", line 116, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./lib/roi_data_layer/roidb.py", line 116, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./lib/roi_data_layer/roidb.py", line 113, in get_roidb
    roidb = get_training_roidb(imdb)
  File "./lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
    imdb.append_flipped_images()
  File "./lib/datasets/imdb.py", line 118, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "./lib/datasets/imdb.py", line 76, in roidb
    self._roidb = self.roidb_handler()
  File "./lib/datasets/sim10k.py", line 133, in gt_roidb
    for index in self.image_index]
  File "./lib/datasets/sim10k.py", line 133, in <listcomp>
    for index in self.image_index]
  File "./lib/datasets/sim10k.py", line 243, in _load_sim10k_annotation
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
KeyError: 'motorbike'
```
To deal with this error ,I add the 'motorbike' and  'person' in self._class in sim10k.py. But what should I do if I only want to detect the car.

PS: Is the test.txt for sim10k is an empty file since all the data in sim10k is used for train?

Thanks!

**Comment by zpge** [comment]
In sim10k.py,
change the function _load_sim10k_annotation(self, index) to

def _load_sim10k_annotation(self, index):
        """
        Load image and bounding boxes info from XML file in the PASCAL VOC
        format.
        """
        filename = os.path.join(self._data_path, 'Annotations_' + self._image_set, index + '.xml')
        tree = ET.parse(filename)
        objs = tree.findall('object')
        # if not self.config['use_diff']:
        #     # Exclude the samples labeled as difficult
        #     non_diff_objs = [
        #         obj for obj in objs if int(obj.find('difficult').text) == 0]
        #     # if len(non_diff_objs) != len(objs):
        #     #     print 'Removed {} difficult objects'.format(
        #     #         len(objs) - len(non_diff_objs))
        #     objs = non_diff_objs
        num_objs = len(objs)

        boxes = np.zeros((num_objs, 4), dtype=np.uint16)
        gt_classes = np.zeros((num_objs), dtype=np.int32)
        overlaps = np.zeros((num_objs, self.num_classes), dtype=np.float32)
        # "Seg" area for pascal is just the box area
        seg_areas = np.zeros((num_objs), dtype=np.float32)
        ishards = np.zeros((num_objs), dtype=np.int32)

        # Load object bounding boxes into a data frame.
        for ix, obj in enumerate(objs):
            labelname = obj.find('name').text.lower().strip()
            if labelname in self._classes:
                bbox = obj.find('bndbox')
                # Make pixel indexes 0-based
                x1 = float(bbox.find('xmin').text) - 1
                y1 = float(bbox.find('ymin').text) - 1
                x2 = float(bbox.find('xmax').text) - 1
                y2 = float(bbox.find('ymax').text) - 1

                diffc = obj.find('difficult')
                difficult = 0 if diffc == None else int(diffc.text)
                ishards[ix] = difficult

                cls = self._class_to_ind[labelname]
                boxes[ix, :] = [x1, y1, x2, y2]
                gt_classes[ix] = cls
                overlaps[ix, cls] = 1.0
                seg_areas[ix] = (x2 - x1 + 1) * (y2 - y1 + 1)

        overlaps = scipy.sparse.csr_matrix(overlaps)

        return {'boxes': boxes,
                'gt_classes': gt_classes,
                'gt_ishard': ishards,
                'gt_overlaps': overlaps,
                'flipped': False,
                'seg_areas': seg_areas}

**Comment by CGguy** [comment]
> Hi! I really appreciate your work and I want to run your code to learn from it . But I met with the following error ,is there a mistake when I deal with the sim10k dataset,I just simply download the dataset and put the anno,images like cityscapes:
> 
> ```
> Traceback (most recent call last):
>   File "train_GPA.py", line 304, in <module>
>     imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
>   File "./lib/roi_data_layer/roidb.py", line 116, in combined_roidb
>     roidbs = [get_roidb(s) for s in imdb_names.split('+')]
>   File "./lib/roi_data_layer/roidb.py", line 116, in <listcomp>
>     roidbs = [get_roidb(s) for s in imdb_names.split('+')]
>   File "./lib/roi_data_layer/roidb.py", line 113, in get_roidb
>     roidb = get_training_roidb(imdb)
>   File "./lib/roi_data_layer/roidb.py", line 97, in get_training_roidb
>     imdb.append_flipped_images()
>   File "./lib/datasets/imdb.py", line 118, in append_flipped_images
>     boxes = self.roidb[i]['boxes'].copy()
>   File "./lib/datasets/imdb.py", line 76, in roidb
>     self._roidb = self.roidb_handler()
>   File "./lib/datasets/sim10k.py", line 133, in gt_roidb
>     for index in self.image_index]
>   File "./lib/datasets/sim10k.py", line 133, in <listcomp>
>     for index in self.image_index]
>   File "./lib/datasets/sim10k.py", line 243, in _load_sim10k_annotation
>     cls = self._class_to_ind[obj.find('name').text.lower().strip()]
> KeyError: 'motorbike'
> ```
> 
> To deal with this error ,I add the 'motorbike' and 'person' in self._class in sim10k.py. But what should I do if I only want to detect the car.
> 
> PS: Is the test.txt for sim10k is an empty file since all the data in sim10k is used for train?
> 
> Thanks!

Hello! I also have a similar question. Have you successfully trained this model now?
